# Generated by Django 5.1 on 2025-02-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_id',
            field=models.CharField(default='d11505', max_length=10, unique=True),
        ),
    ]
