# Generated by Django 5.1 on 2025-02-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_id',
            field=models.CharField(default='fa5f6e', max_length=10, unique=True),
        ),
    ]
